version: "3.9"

services:
  # --- BACKEND (FastAPI) ---
  server:
    build:
      context: .
    container_name: smart_camera_backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
      - mongo_db
    environment:
      # Bạn sẽ khai báo thông tin kết nối DB ở đây để code Python đọc được
      - DB_HOST=mysql_db
      - MONGO_HOST=mongo_db
      - DATABASE_URL=mysql+pymysql://root:123456@mysql_db:3306/smart_camera
      - MONGO_URL=mongodb://mongo_db:27017
    volumes:
      - .:/app
      - ./uploads:/app/uploads # Để lưu trữ ảnh không bị mất khi restart
    restart: always

  # --- DATABASE MYSQL ---
  mysql_db:
    image: mysql:8
    container_name: mysql_db
    environment:
      # CHỖ NHẬP MẬT KHẨU MYSQL Ở ĐÂY
      - MYSQL_ROOT_PASSWORD=123456  # <--- Thay mật khẩu của bạn vào đây
      - MYSQL_DATABASE=smart_camera
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # --- DATABASE MONGODB ---
  mongo_db:
    image: mongo:6
    container_name: mongo_db
    environment:
      - MONGO_INITDB_DATABASE=smart_camera_logs
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mysql_data:
  mongo_data: